# Docker Swarm configuration (for production deployments)
# Usage:
#   docker secret create mqbase.secrets mqbase.secrets
#   docker stack deploy -c compose.swarm.yml mqbase
#
# Credentials are provided via Docker Swarm secrets (most secure):
#   - Create mqbase.secrets file with MQBASE_USER and MQBASE_MQTT_USER
#   - Register as a Docker secret before deploying
#
# Features overlay networking for multi-node Swarm clusters.

services:
  mqbase:
    image: mqbase:${MQBASE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: ${USER_ID:-1000}
        GID: ${GROUP_ID:-1000}
      tags:
      - mqbase:${MQBASE_VERSION:-latest}
    hostname: mqbase
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mqbase-data:/mosquitto/data
      - mqbase-log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    ports:
      - 1883:1883   # MQTT
      - 8883:8883   # MQTT over TLS
      - 8000:8000   # libSQL HTTP
      - 8080:8080   # Admin UI (nginx)
      - 9001:9001   # MQTT over WebSocket
    networks:
      - proxy
    env_file:
      - mqbase.properties
    secrets:
      - mqbase.secrets
    restart: always

secrets:
  mqbase.secrets:
    external: true

volumes:
  mqbase-data:
    name: mqbase-data
  mqbase-log:
    name: mqbase-log

networks:
  proxy:
    driver: overlay
    name: proxy
    attachable: true
